version: "2"

run:
  timeout: 5m
  tests: true
  build-tags:
    - noembed

linters:
  enable:
    - misspell
    - unconvert
    - goconst
    - gosec
    - prealloc
    - nilerr
    - bodyclose
    - errorlint

  settings:
    govet:
      enable-all: true
      disable:
        - fieldalignment
        - shadow

    gosec:
      excludes:
        - G104
        - G304
        - G404
        - G115

    misspell:
      locale: US

    errcheck:
      exclude-functions:
        - (*go.uber.org/zap.Logger).Sync
        - (*go.uber.org/zap.SugaredLogger).Sync
        - (go.uber.org/zap.Logger).Sync
        - github.com/joho/godotenv.Load

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - goconst
          - gosec
          - errcheck
          - errorlint

      - path: embed\.go
        linters:
          - goimports

formatters:
  enable:
    - goimports
    - gofmt

  settings:
    goimports:
      local-prefixes:
        - github.com/irvingmg/skilloper

issues:
  max-issues-per-linter: 50
  max-same-issues: 10
